dubbo:
  application:
    name: dubbo-orm
  registry:
    address: 127.0.0.1:2181
    # 读者请自行更改zookeeper地址
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  #consumer:
  provider:
    check: false
    timeout: 30000

server:
  servlet:
    context-path: /     #路径访问项目名
  encoding:
    force-response: true
  port: 8082              #内置tomcat的自定义启动端口号
  tomcat:
    uri-encoding: utf-8         #tomcat内 传递同步异步数据支持中文
  error:
    whitelabel:
      enabled: false

# MyBatis
mybatis:
  mapperLocations: classpath:mybatis/mapping/*.xml    #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.chinasoft.dubbo_shiro_util.domain  #注意：对应实体类的路径
  configLocation: classpath:mybatis/mybatis.cfg.xml


# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  returnPageInfo: check
  params: count=countSql

spring:
  session: #Spring-session共享 redis 配置
    storeType: redis
    timeout: 30m
    redis:
      flushMode: on_save
      namespace: redis:session
  datasource:
    # mysql 连接区域配置
    name: test
    url: jdbc:mysql://127.0.0.1:3306/shirodemo1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #使用druid数据连接池
    #使用druid数据连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid数据连接池 的持久化性能配置
    filters: stat,wall,slf4j,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    #Nosql连接区域配置
  redis: #添加NoSQL  非关系型数据库的连接配置 redis
    host: 127.0.0.1  #连接数据库的IP地址 我们属于本机安装
    port: 6379  #连接redis数据库端口号
    password: 123456
    database: 0    #Redis数据库索引 （默认为0）
    timeout: 1200  #连接超时时间（毫米）
    lettuce:
      pool: # 连接池各属性配置
        max-active: 8   # 连接池最大连接数 (使用负值表示没有限制)
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接


logging:          #扫描dao层，保证SQL指令在控制台 输出
  level:
    com:
      chinasoft:
        dubbo_shiro_orm:
          mapper: trace

