dubbo:
  application:
    qosEnable: true
    qosPort: 33333
    qosAcceptForeignIp: false
    name:  dubbo-ioc
  registry:
    address: 127.0.0.1:2181
    # 读者请换成自己的zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 30000

server:
  servlet:
    context-path: /     #路径访问项目名
  encoding:
    force-response: true
  port: 8086              #内置tomcat的自定义启动端口号
  tomcat:
    uri-encoding: utf-8         #tomcat内 传递同步异步数据支持中文
  error:
    whitelabel:
      enabled: false




  #thymeleaf 模板配置
spring:
  main:
    allow-bean-definition-overriding: true
  session: #Spring-session共享 redis 配置
    storeType: redis
    timeout: 30m
    redis:
      flushMode: on_save
      namespace: redis:session
    #Nosql连接区域配置
  redis: #添加NoSQL  非关系型数据库的连接配置 redis
    host: 127.0.0.1  #连接数据库的IP地址 我们属于本机安装
    port: 6379  #连接redis数据库端口号
    password: 123456
    database: 0    #Redis数据库索引 （默认为0）
    timeout: 1200  #连接超时时间（毫米）
    lettuce:
      pool: # 连接池各属性配置
        max-active: 8   # 连接池最大连接数 (使用负值表示没有限制)
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  resources:            # static-locations  进行加载/templates/ 与 /static/下的所有静态资源
    static-locations: classpath:/templates/,classpath:/static/,classpath:/dubbo_static/,file:dubbo_static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #热部署文件，页面不产生缓存，及时更新
    cache: false
